#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Ensure .env exists and required platform-provided values are present.
#
# On first run (no .env):  copies .env.example, then prompts interactively.
# On re-runs (.env exists): checks each required key and prompts for any that
#   are still empty — so a partial .env never just hard-errors out.
#
# Secret values auto-generated by billing are handled in generate-secrets.sh.
# ─────────────────────────────────────────────────────────────────────────────

echo "${_group}Checking environment file ..."

if [[ ! -f .env ]]; then
  if [[ ! -f .env.example ]]; then
    error ".env.example not found. Cannot create .env."
    exit 1
  fi

  info "No .env found — copying from .env.example"
  cp .env.example .env
fi

# ---------------------------------------------------------------------------
# Check which platform-provided secrets are still missing.
# ---------------------------------------------------------------------------
# Each entry: "ENV_KEY|hint shown to the user"
_REQUIRED_KEYS=(
  "PLATFORM_DB_PASSWORD|BILLING_APP_DB_PASS from the platform installer output"
  "BILLING_SUPERUSER_PASSWORD|BILLING_SUPERUSER_DB_PASS from the platform installer output"
  "REDIS_PASSWORD|REDIS_PASSWORD from the platform installer output"
  "SERVICE_AUTH_SECRET|INTERNAL_SERVICE_SECRET from the platform installer output"
)

_missing_keys=()
for _entry in "${_REQUIRED_KEYS[@]}"; do
  _key="${_entry%%|*}"
  if [[ -z "$(get_env_value "$_key")" ]]; then
    _missing_keys+=("$_entry")
  fi
done

# ---------------------------------------------------------------------------
# If anything is missing, either prompt interactively or error out.
# ---------------------------------------------------------------------------
if [[ ${#_missing_keys[@]} -gt 0 ]]; then
  if [[ "${NON_INTERACTIVE:-0}" == "1" ]]; then
    error "The following required values are not set in .env:"
    for _entry in "${_missing_keys[@]}"; do
      _key="${_entry%%|*}"
      _hint="${_entry#*|}"
      error "  ${_key}  —  copy ${_hint}"
    done
    exit 1
  fi

  # shellcheck source=scripts/install/collect-config.sh
  source "${SCRIPT_DIR}/collect-config.sh" "${_missing_keys[@]}"
fi

success ".env is present and all required values are set"
echo "${_endgroup}"
